[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.20"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.1.4"

[[constraint]]
  name = "github.com/vidsy/backoff"
  version = "~2.0.0"

[[constraint]]
  name = "github.com/vidsy/go-kmsconfig"
  version = "3.1.0"

[prune]
  go-tests = true
  unused-packages = true
